#!/usr/bin/env bash

# Usage: ./update_dgidb.sh [output_tsv_path]
# Downloads the latest DGIdb TSV dataset, saves it to assets/, 
# and compiles js/dgidb_dataset.js for client-side and agent analysis.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

OUTPUT_TSV="${1:-assets/dgidb_interactions.tsv}"
OUTPUT_JS="js/dgidb_dataset.js"
LICENSE_NOTICE="assets/DGIDB-LICENSE-NOTICES.md"
DOWNLOAD_URL="https://github.com/dgidb/dgidb-data/releases/latest/download/interactions.tsv"

mkdir -p assets js

echo "=========================================="
echo "DGIdb Dataset Updater"
echo "=========================================="
echo "Fetching latest DGIdb dataset from:"
echo "  $DOWNLOAD_URL"

python3 -c "
import urllib.request
import os
import sys

url = '$DOWNLOAD_URL'
out_tsv = '$OUTPUT_TSV'

print(f'Downloading to {out_tsv}...')
try:
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0 (ICARusPox Data Pipeline)'})
    with urllib.request.urlopen(req, timeout=60) as response, open(out_tsv, 'wb') as out_file:
        chunk_size = 1024 * 1024
        downloaded = 0
        while True:
            chunk = response.read(chunk_size)
            if not chunk:
                break
            out_file.write(chunk)
            downloaded += len(chunk)
            print(f'  Downloaded {downloaded / (1024*1024):.2f} MB...', end='\r')
    print(f'\nDownload complete! File size: {os.path.getsize(out_tsv):,} bytes.')
except Exception as e:
    print(f'Error downloading DGIdb TSV: {e}', file=sys.stderr)
    sys.exit(1)
"

if [ ! -f "$OUTPUT_TSV" ]; then
    echo "Error: Output TSV '$OUTPUT_TSV' missing after download!"
    exit 1
fi

echo ""
echo "Compiling $OUTPUT_JS from $OUTPUT_TSV..."

python3 -c "
import csv
import json
import sys

tsv_path = '$OUTPUT_TSV'
out_js = '$OUTPUT_JS'

try:
    gene_map = {}
    total_rows = 0

    with open(tsv_path, 'r', encoding='utf-8', errors='replace') as f:
        # Read header/comment lines
        header_comments = []
        for line in f:
            if line.startswith('#'):
                header_comments.append(line.strip('# \t\r\n'))
            else:
                # First non-comment line is TSV column names
                reader = csv.DictReader([line] + list(f), delimiter='\t')
                break

        for row in reader:
            total_rows += 1
            gene = str(row.get('gene_name', '')).strip().upper()
            drug = str(row.get('drug_name', '')).strip()

            if not gene or not drug or gene == 'NAN' or drug.upper() == 'NAN':
                continue

            is_approved = str(row.get('drug_is_approved', '')).lower() == 'true'
            is_immuno = str(row.get('drug_is_immunotherapy', '')).lower() == 'true'
            is_antineo = str(row.get('drug_is_antineoplastic', '')).lower() == 'true'
            itype = str(row.get('interaction_types', '')).strip() or 'unspecified'
            
            try:
                score = round(float(row.get('interaction_score', 0)), 4)
            except (ValueError, TypeError):
                score = 0.0

            interaction_entry = [drug, is_approved, is_immuno, is_antineo, itype, score]

            if gene not in gene_map:
                gene_map[gene] = []
            
            # Avoid exact duplicate drug-interaction entries for the same gene
            if interaction_entry not in gene_map[gene]:
                gene_map[gene].append(interaction_entry)

    print(f'Processed {total_rows:,} total interaction rows across {len(gene_map):,} unique genes.')

    js_lines = [
        '// DGIdb Gene-Drug Interaction Dataset',
        '// Source: Drug-Gene Interaction Database (DGIdb v5)',
        '// Auto-generated by update_dgidb.sh',
        '// Dataset format per gene: [[drug_name, is_approved, is_immunotherapy, is_antineoplastic, interaction_type, score], ...]',
        'window.DGIDB_DATA = {'
    ]

    sorted_genes = sorted(gene_map.keys())
    for gene in sorted_genes:
        js_lines.append(f'  {json.dumps(gene)}: {json.dumps(gene_map[gene])},')

    js_lines.append('};')
    js_lines.append('')
    js_lines.append('/**')
    js_lines.append(' * Retrieve drug interactions for a specific gene symbol.')
    js_lines.append(' * @param {string} geneSymbol - HGNC gene symbol (case-insensitive)')
    js_lines.append(' * @returns {Array<{drug: string, approved: boolean, immunotherapy: boolean, antineoplastic: boolean, type: string, score: number}>}')
    js_lines.append(' */')
    js_lines.append('window.getGeneDrugInteractions = function(geneSymbol) {')
    js_lines.append('    if (!geneSymbol || !window.DGIDB_DATA) return [];')
    js_lines.append('    const key = String(geneSymbol).toUpperCase().trim();')
    js_lines.append('    const raw = window.DGIDB_DATA[key];')
    js_lines.append('    if (!raw) return [];')
    js_lines.append('    return raw.map(item => ({')
    js_lines.append('        drug: item[0],')
    js_lines.append('        approved: item[1],')
    js_lines.append('        immunotherapy: item[2],')
    js_lines.append('        antineoplastic: item[3],')
    js_lines.append('        type: item[4],')
    js_lines.append('        score: item[5]')
    js_lines.append('    }));')
    js_lines.append('};')
    js_lines.append('')
    js_lines.append('/**')
    js_lines.append(' * Get all gene symbols in the dataset that have approved drug interactions.')
    js_lines.append(' * @returns {string[]}')
    js_lines.append(' */')
    js_lines.append('window.getDruggableGenes = function() {')
    js_lines.append('    if (!window.DGIDB_DATA) return [];')
    js_lines.append('    return Object.keys(window.DGIDB_DATA).filter(g =>')
    js_lines.append('        window.DGIDB_DATA[g].some(item => item[1] === true)')
    js_lines.append('    );')
    js_lines.append('};')

    with open(out_js, 'w', encoding='utf-8') as f:
        f.write('\n'.join(js_lines) + '\n')

    print(f'Successfully compiled {out_js}!')

except Exception as e:
    print(f'Error compiling {out_js}: {e}', file=sys.stderr)
    sys.exit(1)
"

chmod +x "$SCRIPT_DIR/update_dgidb.sh"
echo "=========================================="
echo "DGIdb update complete!"
echo "=========================================="
